In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
holiday = pd.read_csv('HOLIDAY_data/holiday.csv')
covid = pd.read_csv('COVID_cooked_data/COVID_cases_per_day_policy.csv')

##### holiday one hot

In [2]:
holiday_onehot = pd.get_dummies(holiday.iloc[:,1])
holiday_onehot = pd.concat( [ holiday['日期'], holiday_onehot ], axis=1)
holiday_onehot.to_csv(f"HOLIDAY_data/holiday_onehot.csv", index=False)
holiday_onehot

,日期,一般,七夕情人節,中秋節,元宵節,元旦,兒童節,初一,初三,初二,...,民族掃墓節,父親節,端午節,聖誕節,萬聖節,補假,補班,西洋情人節,跨年,除夕
0,2017-01-01,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2017-01-02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,2017-01-03,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2017-01-04,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2017-01-05,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,2022-07-27,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2034,2022-07-28,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2035,2022-07-29,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2036,2022-07-30,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2037,2022-07-31,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

##### covid one hot

In [5]:
covid.columns

Index(['日期', '累積確診人數', '確診人數', '經濟防疫新模式', '二級警戒', '三級警戒', '是否7+7', '是否3+4',
       '首例確診', '口罩實名制', '簡訊實聯制上路', 'Delta變異株', 'Omicron亞型變異株'],
      dtype='object')

In [3]:
new_mode = pd.get_dummies(covid['經濟防疫新模式'])
new_mode.columns = ['無經濟防疫新模式','有經濟防疫新模式']

second_alert = pd.get_dummies(covid['二級警戒'])
second_alert.columns = ['無二級警戒','有二級警戒']

third_alert = pd.get_dummies(covid['三級警戒'])
third_alert.columns = ['無三級警戒','有三級警戒']

seven_seven = pd.get_dummies(covid['是否7+7'])
seven_seven.columns = ['無7+7','有7+7']

three_four = pd.get_dummies(covid['是否3+4'])
three_four.columns = ['無3+4','有3+4']

first_case = pd.get_dummies(covid['首例確診'])
first_case.columns = ['無首例確診','有首例確診']

mask_policy = pd.get_dummies(covid['口罩實名制'])
mask_policy.columns = ['無口罩實名制','有口罩實名制']

sms_report = pd.get_dummies(covid['簡訊實聯制上路'])
sms_report.columns = ['無簡訊實聯制','有簡訊實聯制']

delta_mutate = pd.get_dummies(covid['Delta變異株'])
delta_mutate.columns = ['無Delta變異株','有Delta變異株']

omicron_mutate = pd.get_dummies(covid['Omicron亞型變異株'])
omicron_mutate.columns = ['無Omicron亞型變異株','有Omicron亞型變異株']

list_to_concat = [covid['日期'], covid['累積確診人數'], covid['確診人數'], new_mode, second_alert, third_alert, seven_seven, three_four, 
                 first_case, mask_policy, sms_report, delta_mutate, omicron_mutate]
covid_onehot = pd.concat( list_to_concat, axis=1)
covid_onehot.to_csv(f'COVID_cooked_data/covid_onehot.csv', index=False)
covid_onehot

,日期,累積確診人數,確診人數,無經濟防疫新模式,有經濟防疫新模式,無二級警戒,有二級警戒,無三級警戒,有三級警戒,無7+7,...,無首例確診,有首例確診,無口罩實名制,有口罩實名制,無簡訊實聯制,有簡訊實聯制,無Delta變異株,有Delta變異株,無Omicron亞型變異株,有Omicron亞型變異株
0,2017-01-01,0,0,1,0,1,0,1,0,1,...,1,0,1,0,1,0,1,0,1,0
1,2017-01-02,0,0,1,0,1,0,1,0,1,...,1,0,1,0,1,0,1,0,1,0
2,2017-01-03,0,0,1,0,1,0,1,0,1,...,1,0,1,0,1,0,1,0,1,0
3,2017-01-04,0,0,1,0,1,0,1,0,1,...,1,0,1,0,1,0,1,0,1,0
4,2017-01-05,0,0,1,0,1,0,1,0,1,...,1,0,1,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,2022-07-27,4520777,23934,0,1,1,0,1,0,1,...,0,1,1,0,1,0,0,1,0,1
2034,2022-07-28,4544017,23240,0,1,1,0,1,0,1,...,0,1,1,0,1,0,0,1,0,1
2035,2022-07-29,4565479,21462,0,1,1,0,1,0,1,...,0,1,1,0,1,0,0,1,0,1
2036,2022-07-30,4586523,21044,0,1,1,0,1,0,1,...,0,1,1,0,1,0,0,1,0,1
2037,2022-07-31,4603090,16567,0,1,1,0,1,0,1,...,0,1,1,0,1,0,0,1,0,1